### ISSUE TITLE
CSS may not be set to 100% of browser width (viewed from an iPhone 6 on Safari)

### ISSUE THREAD

**Issue by patricia568** [nep2ne/confectionery-website-prototype#1]
Hello! 
Your website is looking really awesome! But I noticed that your coding may not be set to 100% of the browser width because I can scroll left and right ever so slightly using Safari on the iPhone 6. If this is supposed to happen then you can ignore this message! 

I've attached a screenshot so that you can see better if I did not explain it well enough!

![img-1718](https://user-images.githubusercontent.com/31852223/34673457-55528b58-f450-11e7-869c-092b58bb531f.PNG)
![img-1721](https://user-images.githubusercontent.com/31852223/34673674-10208b7e-f451-11e7-9277-534cc5bc78ef.PNG)

Very good job though on your website!

:)

-Patricia

**Comment by nep2ne** [comment]
Thanks patricia568! I'll look into that!

**Comment by nep2ne** [comment]
Found the problem! Thanks for pointing it out!
