### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by jako-ry** [nep2ne/confectionery-website-prototype#2]
The header is too small for UC browser on mobile — iPhone — likely due to the boxes on the sweets page.

**Comment by nep2ne** [comment]
Thanks - would you be able to show me a screenshot? I'm not sure what you mean by the header being too small...

**Comment by jako-ry** [comment]
Sorry, here you go:

![img_3331](https://user-images.githubusercontent.com/31830914/34676069-8c2fd1a4-f459-11e7-8bb0-f89ddcc059f0.PNG)

It's the same problem as what someone else pointed out. It appears to work fine when you load the page but you can actually scroll to the side or zoom out.

**Comment by nep2ne** [comment]
Thanks - that's a good comment. I think I've fixed the issue by removing the item that was forcing the page to spill to the right.
